---
swagger: "2.0"
info:
  description: "This is a sample."
  version: "v1"
  title: "Swagger Maven Plugin Sample"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8081"
basePath: "/api"
schemes:
- "http"
- null
paths:
  /gobii/v1/auth:
    post:
      summary: "authorization"
      description: ""
      operationId: "authenticate"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
securityDefinitions:
  basicAuth:
    type: "basic"
