export enum ExtractorItemType {
    UNKNOWN,
    ENTITY,
    MARKER_INPUT_FILE,
    MARKER_LIST_ITEM,
    SAMPLE_LIST_ITEM,
    SAMPLE_INPUT_FILE,
    EXPORT_FORMAT,
    CROP_TYPE,
    JOB_ID,
    SAMPLE_LIST_TYPE,
    LABEL,    TREE_STRUCTURE,
    VERTEX,
    VERTEX_VALUE,
    ITEM_COUNT,
    MARKER_RESULT_FILE,
    SAMPLE_RESULT_FILE
}
